# Generated by Django 6.0.7 on 2026-07-12 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("asset_tag", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                            ("Damaged", "Damaged"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="assets/photos/"
                    ),
                ),
                ("is_bookable", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Allocated", "Allocated"),
                            ("Reserved", "Reserved"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Lost", "Lost"),
                            ("Retired", "Retired"),
                            ("Disposed", "Disposed"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="organization.assetcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_date", models.DateField()),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Returned", "Returned")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("checkin_condition_notes", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="organization.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="assets/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Requested", "Requested"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Re-allocated", "Re-allocated"),
                        ],
                        default="Requested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests",
                        to="assets.allocation",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_for_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_received",
                        to="organization.department",
                    ),
                ),
                (
                    "requested_for_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Active")),
                fields=("asset",),
                name="unique_active_allocation_per_asset",
            ),
        ),
    ]
